name: Gamemode
main: Gamemode\Steellgold\Main
version: 1.0-Dev
api: 3.0.0
author: Steellgold

commands:
  gm1:
    description: "§f[§3Gamemode§f]§r > Creative"
    usage: "/gm1"
    permission: "steellgold.gm1"


  gm2:
    description: "§f[§3Gamemode§f]§r > Adventure"
    usage: "/gm2"
    permission: "steellgold.gm2"

  gm3:
    description: "§f[§3Gamemode§f]§r > Spectator"
    usage: "/gm3"
    permission: "steellgold.gm3"

  gm0:
    description: "§f[§3Gamemode§f]§r > Survival"
    usage: "/gm0"
    permission: "steellgold.gm0"

permissions:
 steellgold.gm1:
  default: op
 steellgold.gm2:
  default: op
 steellgold.gm3:
  default: op
 steellgold.gm0:
  default: op
